### ISSUE TITLE
平均値を小数点第1位まで表示したい

### ISSUE THREAD

**Issue by satoke** [yoshimaru46/planning-poker#7]
人が選ぶ値としてはフィボナッチ数が良いとされているが、それらの平均をとったポイントについてはフィボナッチ数ではなくてもよいので、小数点第2位を切り上げて小数点第1位まで表示したい。

**Comment by satoke** [comment]
正月やることないので正月にやります。

**Comment by yoshimaru46** [comment]
こちらも対応しました 👍
