### ISSUE TITLE
0.5はフィボナッチ数ではないので削除したい

### ISSUE THREAD

**Issue by satoke** [yoshimaru46/planning-poker#8]
0.5はフィボナッチ数ではないので削除したい。
その代わりに１３と２１のカードを追加したい。

**Comment by satoke** [comment]
正月やることないので正月にやります。

**Comment by yoshimaru46** [comment]
さとけさんーお久しぶりです！！
フィードバックありがとうございます！
対応しました 👍 

![Screen Shot 2021-01-17 at 22 58 21](https://user-images.githubusercontent.com/19199223/104845223-8e36ad80-5917-11eb-9efb-2b06139af9e0.png)

**Comment by satoke** [comment]
お久しぶりですーお元気ですか？
助かりました！職場で使わせていただいてますー。
嫁のつわり対応で正月が終わって何もできずすいません 🙏
